CASES_DIR: "./cases"
CASES_PREFIX: "/home/marsdenlab/datasets/vascular_data"

LEAK: 0.2
BATCH_SIZE: 4
LEARNING_RATE: 0.001
TRAIN_STEPS: 25000
PRINT_STEP: 50
INIT: 0.07
L2_REG: 0.0000
NUM_FILTERS: 32
QUEUE_SIZE: 50
NUM_THREADS: 200
THRESHOLD: 0.2
PR_INTERVALS: 30
NUM_CONTOUR_POINTS: 10
